FROM node:14.15.4
WORKDIR /app
COPY ./build /app
RUN npm install
EXPOSE 80
ARG HOST=${HOST}
ARG PORT=${PORT}
ARG NODE_ENV=${NODE_ENV}
ARG APP_KEY=${APP_KEY}
ARG DB_CONNECTION=${DB_CONNECTION}
ARG PG_HOST=${PG_HOST}
ARG PG_PORT=${PG_PORT}
ARG PG_USER=${PG_USER}
ARG PG_PASSWORD=${PG_PASSWORD}
ARG PG_DB_NAME=${PG_DB_NAME}
CMD ["npm", "start"]
